"""empty message

Revision ID: c1f66f6a71f8
Revises: 
Create Date: 2025-06-25 09:14:24.432059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f66f6a71f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_professional', sa.Boolean(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('firstname', sa.String(length=150), nullable=True),
    sa.Column('lastname1', sa.String(length=150), nullable=True),
    sa.Column('lastname2', sa.String(length=150), nullable=True),
    sa.Column('address_street', sa.String(length=150), nullable=True),
    sa.Column('address_city', sa.String(length=150), nullable=True),
    sa.Column('address_postcode', sa.String(length=20), nullable=True),
    sa.Column('address_county', sa.String(length=150), nullable=True),
    sa.Column('address_country', sa.String(length=150), nullable=True),
    sa.Column('tax_number', sa.String(length=15), nullable=True),
    sa.Column('geo_dir', sa.String(length=150), nullable=True),
    sa.Column('active_user', sa.Boolean(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professionals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prof_experience', sa.String(length=15000), nullable=True),
    sa.Column('prof_url', sa.String(length=80), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(length=300), nullable=True),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remote_project', sa.Boolean(), nullable=True),
    sa.Column('project_city', sa.String(length=150), nullable=True),
    sa.Column('project_county', sa.String(length=150), nullable=True),
    sa.Column('project_country', sa.String(length=150), nullable=True),
    sa.Column('post_description', sa.String(length=1500), nullable=True),
    sa.Column('estimated_budged', sa.String(length=100), nullable=True),
    sa.Column('post_open', sa.Boolean(), nullable=True),
    sa.Column('post_active', sa.Boolean(), nullable=True),
    sa.Column('post_completed', sa.Boolean(), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premiums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('renewal_date', sa.DateTime(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('auto_renewal', sa.Boolean(), nullable=False),
    sa.Column('premium_types', sa.String(length=10), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating_professional', sa.Enum('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', name='ratingvalue'), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidature_message', sa.String(length=1500), nullable=False),
    sa.Column('candidature_date', sa.DateTime(), nullable=False),
    sa.Column('candidature_status', sa.Enum('IN_PROCESS', 'ACCEPTED', 'REJECTED', name='candidaturestatus'), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agreement_date', sa.DateTime(), nullable=True),
    sa.Column('agreement_status', sa.Enum('IN_PROCESS', 'ACCEPTED', 'REJECTED', name='candidaturestatus'), nullable=False),
    sa.Column('candidature_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('professional_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidature_id'], ['candidatures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agreements')
    op.drop_table('candidatures')
    op.drop_table('ratings')
    op.drop_table('premiums')
    op.drop_table('posts')
    op.drop_table('payments')
    op.drop_table('comments')
    op.drop_table('professionals')
    op.drop_table('clients')
    op.drop_table('users')
    op.drop_table('plans')
    op.drop_table('categories')
    # ### end Alembic commands ###
